# Generated by Django 5.2.4 on 2025-07-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField()),
                ("message_id", models.IntegerField()),
                ("user_message", models.TextField()),
                ("agent_messages", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "conversations",
                "indexes": [
                    models.Index(
                        fields=["chat_id"], name="conversatio_chat_id_624d8d_idx"
                    ),
                    models.Index(
                        fields=["message_id"], name="conversatio_message_0a32f7_idx"
                    ),
                ],
            },
        ),
    ]
