import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
  send: (channel: string, data: any) => ipcRenderer.send(channel, data),
  changeMode: (mode: any) => ipcRenderer.send('change-mode', mode),
  openExternal: (href: string) => ipcRenderer.send('open-external', href),
  toggleAutoOpt: () => ipcRenderer.send('toggle-auto-opt'),
  streamMessageStop: () => ipcRenderer.send('stream-message-stop'),
  renameChat: (data: Record<string, any>) => ipcRenderer.send('rename-chat', data),
  delChat: (id: any) => ipcRenderer.send('del-chat', id),
  setGlobal: (chat: any) => ipcRenderer.send('set-global', chat),
  showLog: (data: Record<string, any>) => ipcRenderer.send('show-log', data),
  startAgentLoop: (callback: (data: Record<string, any>) => void) => ipcRenderer.on('startAgentLoop', (_event, data) => callback(data)),
  handleExtraLoad: (callback: (data: Record<string, any>) => void) => ipcRenderer.on('extra_load', (_event, data) => callback(data)),
  handleOptions: (callback: (data: Record<string, any>) => void) => ipcRenderer.on('options', (_event, data) => callback(data)),
  handleClear: (callback: (value: any) => void) => ipcRenderer.on('clear', (_event, value) => callback(value)),
  initInfo: (callback: (info: any) => void) => ipcRenderer.on('init-info', (_event, info) => callback(info)),
  setPrompt: (callback: (prompt: any) => void) => ipcRenderer.on('prompt', (_event, prompt) => callback(prompt)),
  handleLog: (callback: (log: any) => void) => ipcRenderer.on('log', (_event, log) => callback(log)),
  handleMarkDownFormat: (callback: (status: any) => void) => ipcRenderer.on('markdown-format', (_event, markdown_statu) => callback(markdown_statu)),
  handleReactStatu: (callback: (status: any) => void) => ipcRenderer.on('react-statu', (_event, react_statu) => callback(react_statu)),
  handleChangeMode: (callback: (mode: any) => void) => ipcRenderer.on('change-mode', (_event, mode) => callback(mode)),
  handleDeleteMemory: (callback: (data: Record<string, any>) => void) => ipcRenderer.on('delete-memory', (_event, data) => callback(data)),
  toolData: (callback: (chunk: any) => void) => ipcRenderer.on('toolData', (_event, chunk) => callback(chunk)),
  streamData: (callback: (chunk: any) => void) => ipcRenderer.on('streamData', (_event, chunk) => callback(chunk)),
  infoData: (callback: (info: any) => void) => ipcRenderer.on('infoData', (_event, info) => callback(info)),
  userData: (callback: (info: any) => void) => ipcRenderer.on('userData', (_event, info) => callback(info)),
  uploadProgress: (callback: (info: any) => void) => ipcRenderer.on('upload-progress', (_event, info) => callback(info)),
  handleNewChat: (callback: (chat: any) => void) => ipcRenderer.on('new-chat', (_event, chat) => callback(chat)),
  handleSelectChat: (callback: (chat: any) => void) => ipcRenderer.on('select-chat', (_event, chat) => callback(chat)),
  handleSetChat: (callback: (chat: any) => void) => ipcRenderer.on('set-chat', (_event, chat) => callback(chat)),
  handleAutoRenameChat: (callback: (chat: any) => void) => ipcRenderer.on('auto-rename-chat', (_event, chat) => callback(chat)),
  agentLoop: (data: Record<string, any>) => ipcRenderer.invoke('agentLoop', data),
  getFilePath: () => ipcRenderer.invoke('get-file-path'),
  captureRegion: (params: any) => ipcRenderer.invoke('capture-region', params),
  toggleMessageGroup: (data: Record<string, any>) => ipcRenderer.invoke('toggleMessageGroup', data),
  compressionGroupMessage: (data: Record<string, any>) => ipcRenderer.invoke('compressionGroupMessage', data),
  thumbMessageGroup: (data: Record<string, any>) => ipcRenderer.invoke('thumbMessageGroup', data),
  toggleContextMessage: (context_id: any) => ipcRenderer.invoke('toggleContextMessage', context_id),
  newChat: () => ipcRenderer.invoke('new-chat'),
  loadChat: (id: any) => ipcRenderer.invoke('load-chat', id),
  getConfig: () => ipcRenderer.invoke('get-config-main'),
  setConfig: (config: any) => ipcRenderer.invoke('set-config-main', config),
  Envs: (data: Record<string, any>) => ipcRenderer.invoke('envs', data),
  Tasks: (data: Record<string, any>) => ipcRenderer.invoke('tasks', data),
});