export declare function delete_message(id: any): Promise<void>;
export declare function compression_message(id: any): Promise<void>;
export declare function thumbMessage(up: HTMLElement, down: HTMLElement, data: any): Promise<void>;
export declare function locate_memory(context_id: number): void;
export declare function quote_memory(context_id: number): void;
export declare function delete_memory(context_id: number): Promise<void>;
export declare function menuEvent(messageSystem: HTMLElement, message_content: HTMLElement, is_plugin: boolean): void;
export declare function addEventStop(messageSystem: HTMLElement): void;
export declare function userAdd(data: any): Promise<void>;
export declare function infoAdd(info: any): Promise<void>;
export declare function streamMessageAdd(chunk: any): Promise<void>;
